services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_residencia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: residencia_db
      MYSQL_USER: user_residencia
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"